<?php
/** @var \Magere\Entity\View\Helper\ModuleHelper $entityHelper */
$entityHelper = $this->entity();

$controller = $this->layout()->route->getParam('controller');
$action = $this->layout()->route->getParam('action');
?>

<?=$this->form()->openTag($form)?>
	<table class="CmsMainText table-content tableborder tableinput">
		<thead>
		<tr class="CmsHeader">
			<td width="200" align="center">Параметр</td>
			<td width="400" align="left">Значение</td>
		</tr>
		</thead>
		<tbody>
		<tr>
			<td><?=$buyerFields['category']?></td>
			<td>
				<?php $formName = $form->get('entityId'); ?>
				<select name="entityId"><?=$entityHelper->entityList($formName->getValue(), 'Выберите категорию')?></select>
				<?=$this->formElementerrors($formName)?>
			</td>
		</tr>
		<tr>
			<td><?=$buyerFields['status']?></td>
			<td><?=$this->formRow($form->get('name'))?></td>
		</tr>
		</tbody>
		<tfoot>
		<tr>
			<td colspan="2">
				<div class="button-place">
					<?php
					$buttonsArgs['save'] = [
						'type'       => 'submit',
						'attr'       => [
							'class' => 'button',
						],
						'controller' => $controller,
						'action'     => $action,
					];

					echo $this->buttons('saveItem', $buttonsArgs);
					?>
				</div>
			</td>
		</tr>
		</tfoot>
	</table>
<?=$this->form()->closeTag()?>