<?php
$controller = $this->current('route')->getParam('controller');
$action = $this->current('route')->getParam('action');

/*$controller = $this->layout()->route->getParam('controller');
$this->plugin('translate')->setTranslatorTextDomain('Magere\Permission');*/
?>

<div class="header-content-layout form-header">
	<ul class="line1">
		<li>
			<?php /*=$this->buttons('addItem', ['add' => [
				'href'			=> $this->url('default', [
					'controller'	=> $controller,
					'action'		=> 'add'
				]),
				'controller'	=> $controller,
				'action'		=> 'add',
			]])*/?>
		</li>
	</ul>
</div>

<p><a class="btn btn-success btn-lg"
	  href="<?= $this->url('default', ['controller' => $controller, 'action' => 'add']); ?>"
	  target="_blank"><?php echo $this->translate('Добавить статус') ?> &raquo;</a></p>

<div class="body-content-layout">
	<div class="panel-fixed">

	<!-- content -->
	<!--<table class="table-content tableborder width ankets_tbl">
		<thead class="CmsHeader">
		<tr>
			<td><?/*=$buyerFields['id']*/?></td>
			<td><?/*=$buyerFields['status']*/?></td>
			<td><?/*=$buyerFields['category']*/?></td>
			<td></td>
		</tr>
		</thead>
	</table>-->

</div>
<table class="cmsMainText ankets_tbl tableborder table-content table-info-row">
	<tbody>
	<?php foreach ($items as $item) { ?>
		<tr>
			<td><?=$item->getId()?></td>
			<td>
				<a href="<?=$this->url('default/id', [
					'controller'	=> $controller,
					'action'		=> 'edit',
					'id'			=> $item->getId()
				])?>"><?=$item->getName()?></a>
			</td>
			<td><?=$this->translate($item->getMnemo())?></td>
			<td><?=$this->translate($item->getModule()->getNamespace())?></td>
			<td>
				<input type="hidden" name="id" value="<?=$item->getId()?>">
				<?php
				/*$buttonsArgs['delete'] = [
					'href'			=> $this->url('default/id', [
						'controller'	=> $controller,
						'action'		=> 'delete',
						'id'			=> $item[0]->getId()
					]),
					'class'			=> $controller,
					'controller'	=> $controller,
					'action'		=> 'delete',
				];
				echo $this->buttons('deleteItem', $buttonsArgs);*/
				?>
				<p><a class="btn btn-success btn-lg"
					  href="<?= $this->url('default/id', ['controller' => $controller, 'action' => 'delete', 'id' => $item->getId()]); ?>"
					  target="_blank"><?php echo $this->translate('Удалить статус') ?> &raquo;</a>
				</p>
			</td>
		</tr>
	<?php } ?>
	</tbody>
</table>
</div>